# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bym_scale <- function(Q_) {
    .Call('_BYMScale_bym_scale', PACKAGE = 'BYMScale', Q_)
}

